<?php
 
//Include needed php classes 
include_once('classes/ClientID.inc'); 
include_once('classes/ViewRecord.inc');
include_once('classes/UTMQuery.inc');



/*
    Extracts relavent Google Analytics tracking information
*/
//only works if ga.js (Classic Tracking) is being used, rather than analytics.js (Universal) 
function extract_utm_codes() {
    $parsed_utm_tokens = new UTM($_COOKIE);
    return $parsed_utm_tokens->getAllTokens();
} 

/*
* Gets the google analytics client id
*/ 
function extract_client_id() {
    $current_user = new ClientID($_COOKIE);
    return $current_user->GetClientID();
} 

function check_var ($var) {
    if(!isset($var)) {
        return '';
    } else {
        return $var;
    }
}

/* 
*   Implements hook_page_alter()
*/
function gacsom_boot() {

    //Keep track of UTM codes on the client side for efficiency
    if (!isset($_COOKIE["_GACSOM_UTM"])) {
        
        if (isset($_GET['utm_campaign'])) {
            //save the current time and UTM values, then set the cookie for one year
            setcookie("_GACSOM_UTM", check_var($_GET["utm_source"]).'.'.check_var($_GET["utm_medium"]).'.'.$_GET["utm_campaign"].'.'.currentTimeMillis(), time() + (126144000), "/");
        }
    
    //if there is no cookie, then create one only if there is a campaign
    } else {
        
        if (isset($_GET['utm_campaign'])) {
            //if the current UTM codes are newer than what is saved in the cookie, update the cookie with the current ones.
            setcookie("_GACSOM_UTM", check_var($_GET["utm_source"]).'.'.check_var($_GET["utm_medium"]).'.'.$_GET["utm_campaign"].'.'.currentTimeMillis(), time() + (126144000), "/");
        }

    } 
    
    //Make sure we are not recording multiple view hits to the database by the user refreshing the page
    //set the cookie for one hour for the entire site
    if(!isset($_COOKIE['_GACSOM'])) {
        setcookie("_GACSOM", $_GET['q'], time() + (86400/12), "/");
    }  else {
        if (strcmp($_GET['q'], $_COOKIE['_GACSOM']) == 0) {
            return;
        } else {
            setcookie("_GACSOM", $_GET['q'], time() + (86400/12), "/");
        }
    }

    //Collect information about the current page 
    $record = gacsom_build_record();

    //save the data to the database
    gacsom_set_record($record);
} 

//get the current time in milliseconds
function currentTimeMillis() {
    list($usec, $sec) = explode(" ", microtime());
    return round(((float)$usec + (float)$sec) * 1000);
}


/*
*   Build a record to be saved
*/
function gacsom_build_record() {
    
    //pull the UTM variables
    if (isset($_GET["utm_source"])) {
        $source = $_GET["utm_source"];
    } else {
        $source = '';
    }

    if (isset($_GET["utm_medium"])) {
        $medium = $_GET["utm_medium"];
    } else {
        $medium = '';
    }

    if (isset($_GET["utm_campaign"])) {
        $campaign = $_GET["utm_campaign"];  
    } else {
        $campaign = '';
    }

    //get the Google Analytics client id
    $client_id = extract_client_id();
    
    $date = currentTimeMillis();

    $url = $_GET['q'];
    
    $record = new ViewRecord($source, $medium, $campaign, $client_id, $date, $url);

    return $record;
}
 
/*
*	  Save a record
*/ 
function gacsom_set_record($record) {
    $result = db_insert('gacsom')
        ->fields(array(
            'source' => $record->source,
			'medium' => $record->medium,
			'campaign' => $record->campaign,
			'client_id' => (string) $record->client_id,
			'url' => $record->url,
            'time' => (string) $record->date,
    ))
    
    ->execute();

    return $result;
}

/*
* implements hook_form_alter()
*/
//Attach to every form our custom validation handler
function gacsom_form_alter(&$form, &$form_state, $form_id) {
    $form['#validate'][] = 'gacsom_form_validate';
}

/*
* implements hook_form_validate()
*/
//Run on every form submitted in order to capture any identifying information so to then associate 
//with the Google Analytics client id
function gacsom_form_validate($form_id, &$form_state) {
    
    
    // $email = $form_state["values"];
    // dpm($form_state);
}

/*
* implements hook_additional_post_variables_alter()
*/
function gacsom_insert_additional_post_variables_alter(&$content) {

    //Grab google analytics client id and use it for a database query
    $client_id = extract_client_id();

    //For efficiency, check to see if the UTM codes are saved in the "_GACSOM_UTM" cookie, else pull from the database. 
    if (!isset($_COOKIE["_GACSOM_UTM"])) {
        $utm_query = new UTMQuery($client_id);
        $result = $utm_query->get_most_recent_utm_history();
        $content[] = $result->fetchAll();
    } else {
        $utm_values = $_COOKIE["_GACSOM_UTM"];
        $values = explode('.', $utm_values);    
        $values[] =  $client_id;
        $content[] = $values;
    }

    dpm($content);

}